repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
    -   id: ruff-check
        args: [--fix]
        exclude: ^addons_oca/
    -   id: ruff-format
        exclude: ^addons_oca/
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
    -   id: bandit
-   repo: local
    hooks:
    -   id: eradicate
        name: eradicate (dead/commented-out code)
        entry: eradicate --error
        language: python
        additional_dependencies: ["eradicate"]
        types: [python]
    -   id: pylint-odoo
        name: pylint-odoo
        entry: pylint --rcfile=.pylintrc
        language: python
        additional_dependencies: ["pylint-odoo==10.0.6"]
        types: [python]
        exclude: ^addons_oca/
