from . import hr_attendance
from . import hr_employee
from . import hr_payslip
from . import hr_work_entry
from . import hr_attendance_overtime_resource_calendar
from . import hr_attendance_overtime_with_datetimes
from . import hr_leave_type
from . import res_config_settings
from . import hr_contract
