# -*- coding: utf-8 -*-
import logging

from markupsafe import Markup

from odoo import _, fields, models
from odoo.tools import formatLang

_logger = logging.getLogger(__name__)


class SaleOrder(models.Model):
    _inherit = 'sale.order'

    website_customer_confirmed = fields.Boolean(
        string="Confirmed by Customer (Website)",
        copy=False,
        readonly=True,
        help="Checked when the order was confirmed by the customer from the website"
             " (eCommerce payment or signature on the portal).",
    )

    website_manual_payment_requested = fields.Boolean(
        string="Manual Payment Requested (Website)",
        copy=False,
        readonly=True,
        help="Checked when the customer validated their cart while online payment was not"
             " available: the quotation has been sent to the sales team, which will contact"
             " the customer to finalize the order.",
    )

    def action_confirm(self):
        res = super().action_confirm()
        web_orders = self.filtered(
            lambda so: so.state == 'sale'
            and not so.website_customer_confirmed
            and so._is_confirmed_from_website()
        )
        if web_orders:
            web_orders = web_orders.sudo()
            web_orders.website_customer_confirmed = True
            web_orders._schedule_website_confirmation_activities()
        return res

    def _is_confirmed_from_website(self):
        self.ensure_one()
        # eCommerce order, or confirmation made by the customer themselves
        # (portal signature/payment) rather than by an internal user.
        return bool(self.website_id) or not self.env.user._is_internal()

    def _schedule_website_confirmation_activities(self):
        for order in self:
            company = order.company_id

            # The sales team has already been notified when the customer requested
            # a manual follow-up at checkout: do not duplicate that activity.
            if not order.website_manual_payment_requested:
                sale_users = order._get_website_sale_activity_users()
                order._schedule_web_activity(
                    sale_users,
                    _("Sales follow-up — web order confirmed"),
                    _(
                        "Customer %(customer)s confirmed order %(order)s on the website."
                        " Please follow up on this sale.",
                        customer=order.partner_id.display_name,
                        order=order.name,
                    ),
                )

            # One activity per delivery order generated by the confirmation.
            for picking in order.picking_ids:
                delivery_users = (
                    company.website_confirm_delivery_activity_user_ids
                    or picking.user_id
                    or order.user_id
                )
                picking._schedule_web_activity(
                    delivery_users,
                    _("Prepare delivery — web order %s", order.name),
                    _(
                        "Web order %(order)s from customer %(customer)s has been confirmed."
                        " Please process delivery order %(picking)s.",
                        order=order.name,
                        customer=order.partner_id.display_name,
                        picking=picking.name,
                    ),
                )

    def _create_invoices(self, grouped=False, final=False, date=None):
        # The invoice of a web order confirmed by the customer is followed up by
        # the finance team as soon as it is created.
        moves = super()._create_invoices(grouped=grouped, final=final, date=date)
        for move in moves.sudo().filtered(lambda m: m.move_type == 'out_invoice'):
            orders = move.line_ids.sale_line_ids.order_id.filtered(
                'website_customer_confirmed'
            )
            if not orders:
                continue

            invoice_users = (
                move.company_id.website_confirm_invoice_activity_user_ids
                or move.invoice_user_id
                or orders[:1].user_id
            )
            move._schedule_web_activity(
                invoice_users,
                _("Invoicing follow-up — web order %s", ", ".join(orders.mapped('name'))),
                _(
                    "Invoice %(move)s has been generated for web order %(order)s of customer"
                    " %(customer)s. Please follow up on the invoicing.",
                    move=move.name or move.payment_reference or "",
                    order=", ".join(orders.mapped('name')),
                    customer=move.partner_id.display_name,
                ),
            )
        return moves

    # === MANUAL PAYMENT (ONLINE PAYMENT NOT AVAILABLE YET) === #

    def _get_website_sale_activity_users(self):
        """ Users to notify on the quotation of a web order. """
        self.ensure_one()
        return (
            self.company_id.website_confirm_sale_activity_user_ids
            or self.user_id
            or self.team_id.user_id
        )

    def _process_website_manual_payment_request(self):
        """ Handle the checkout validation when online payment is not available.

        No payment transaction is created: the cart is turned into a sent
        quotation and the sales team is asked to contact the customer.
        """
        for order in self:
            if order.state == 'draft':
                order.action_quotation_sent()
            order.website_manual_payment_requested = True
            order._schedule_manual_payment_activity()

    def _schedule_manual_payment_activity(self):
        self.ensure_one()
        self._schedule_web_activity(
            self._get_website_sale_activity_users(),
            _("Web order to be processed — %s", self.name),
            self._get_manual_payment_activity_note(),
        )

    def _get_manual_payment_activity_note(self):
        """ Activity body: quotation number, order total and ordered products. """
        self.ensure_one()

        contact = [self.partner_id.display_name]
        if self.partner_id.email:
            contact.append(self.partner_id.email)
        if self.partner_id.phone or self.partner_id.mobile:
            contact.append(self.partner_id.phone or self.partner_id.mobile)

        products = Markup().join(
            Markup("<li>%(product)s — %(quantity)s x %(price)s = %(subtotal)s</li>") % {
                'product': line.product_id.display_name or line.name,
                'quantity': formatLang(self.env, line.product_uom_qty),
                'price': formatLang(self.env, line.price_unit, currency_obj=self.currency_id),
                'subtotal': formatLang(
                    self.env, line.price_subtotal, currency_obj=self.currency_id
                ),
            }
            for line in self.order_line.filtered(lambda sol: not sol.display_type)
        )

        return Markup(
            "<p>%(intro)s</p>"
            "<ul>"
            "<li>%(quotation)s</li>"
            "<li>%(total)s</li>"
            "<li>%(customer)s</li>"
            "</ul>"
            "<p>%(products_title)s</p>"
            "<ul>%(products)s</ul>"
        ) % {
            'intro': _(
                "Online payment is not available yet: the customer validated their cart on"
                " the website and is waiting to be contacted by the sales team."
            ),
            'quotation': _("Quotation: %s", self.name),
            'total': _(
                "Order total: %s",
                formatLang(self.env, self.amount_total, currency_obj=self.currency_id),
            ),
            'customer': _("Customer: %s", " · ".join(contact)),
            'products_title': _("Ordered products:"),
            'products': products,
        }


class MailActivityMixin(models.AbstractModel):
    _inherit = 'mail.activity.mixin'

    def _schedule_web_activity(self, users, summary, note):
        """ Schedule a "To Do" activity for each of the given internal users. """
        internal_users = users.filtered(lambda u: u.active and u._is_internal())
        if not internal_users:
            _logger.warning(
                "tanatech_website_sale: no internal user to assign the activity"
                " '%s' on %s; activity not created.",
                summary,
                self,
            )
            return

        for record in self:
            for user in internal_users:
                record.activity_schedule(
                    'mail.mail_activity_data_todo',
                    user_id=user.id,
                    summary=summary,
                    note=note,
                )
